packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  '@scarf/scarf': set this to true or false
  bigint-buffer: true
  bufferutil: set this to true or false
  utf-8-validate: set this to true or false
onlyBuiltDependencies:
  - bufferutil
  - utf-8-validate
